const simulatedImages = [
        'ariel_1.jpg', 
        'bacchus_1.png',
        'bacchus_2.png',
        'callisto_1.jpeg',
        'castalia_1.gif', 
        'ceres_1.jpeg', 
        'ceres_2.jpeg', 
        'charon_1.jpg', 
        'dactyl_1.jpg',
        'deimos_1.jpeg', 
        'despina_1.jpg', 
        'dione_1.jpeg', 
        'dione_2.jpeg', 
        'dione_3.jpeg', 
        'dione_4.jpeg', 
        'earth_1.jpeg', 
        'enceladus_1.jpeg', 
        'eris_1.jpg', 
        'eros_1.jpg',
        'europa_1.jpeg',
        'europa_2.jpeg',
        'galatea_1.jpg',
        'ganymede_1.jpeg',
        'gaspra_1.jpg',
        'geographos_1.png',
        'geographos_2.png',
        'golevka_1.jpeg',
        'haumea_1.png',
        'iapetus_1.jpg',
        'iapetus_2.jpg',
        'io_1.jpeg',
        'io_2.jpeg',
        'ida_dactyl_1.jpg',
        'ida_dactyl_2.jpg',
        'juno_1.jpg',
        'jupiter_1.jpeg',
        'jupiter_2.jpeg',
        'jupiter_3.jpeg',
        'jupiter_europa_1.png',
        'kleopatra_1.jpg',
        '1998 ky26_1.jpg',
        'larissa_1.gif',
        'mathilde_1.jpg',
        'makemake_1.jpeg',
        'mars_1.png',
        'mars_2.jpeg',
        'mercury_1.jpeg',
        'mimas_1.jpeg',
        'miranda_1.jpeg',
        'miranda_2.jpeg',
        'moon_1.png',
        'moon_2.png',
        'moon_3.jpeg',
        'neptune_1.jpeg',
        'nereid_1.jpg',
        'oberon_1.jpg',
        'pallas_1.jpg',
        'pallas_2.png',
        'phobos_2.jpeg',
        'pluto_1.jpeg',
        'pluto_2.jpeg',
        'pluto_3.jpg',
        'pluto_4.jpeg',
        'proteus_1.jpg',
        'rhea_1.jpeg',
        'rhea.jpeg',
        'saturn_1.jpeg',
        'saturn_2.jpeg',
        'saturn_3.jpeg',
        'saturn_4.jpeg',
        'saturn_5.png',
        'saturn_6.jpeg',
        'sun_2.jpg',
        'sun_1.jpg',
        'tethys_1.jpeg',
        'titan_1.jpeg',
        'titan_2.jpeg',
        'titan_rhea_1.jpeg',
        'titan_saturn_1.jpeg',
        'titania_1.jpg',
        'titania_2.jpg',
        'toutatis_1.jpg',
        'triton_1.jpeg',
        'umbriel_1.jpg',
        'uranus_1.jpeg',
        'uranus_2.jpeg',
        'uranus_3.jpeg',
        'venus_1.jpeg',
        'venus_2.jpeg',
        'vesta_1.png'

        // Add more as needed
    ];
    
const imageCredits = { 
    "sun_1": 'NASA',
    "sun_2": 'ESA',
    "bacchus_1": 'JPL BENNER ET AL 1998',
    "bacchus_2": 'JPL BENNER ET AL 1998',
    "mercury_1": 'NASA',
    "venus_1": 'JAXA / ISAS / DARTS / Damia Bouic',
    "venus_2": 'NASA JPL CALTECH',
    "moon_1": `Change'e 5-T1`,
    "moon_2": `ISS / @MAstronomer`,
    "moon_3": `NASA/GSFC/Arizona State University`,
    "mimas_1": 'Cassini / NASA',
    "mars_1": '@MAstronomer',
    "mars_2": '@MAstronomer',
    "mathilde_1": 'NASA/JPL NEAR Spacecraft June 27, 1997',
    "phobos_1": 'Phobos 2 Spacecraft',
    "ceres_1": 'NASA Dawn Spacecraft',
    "ceres_2": 'NASA Dawn Spacecraft',
    "dactyl_1": 'NASA/JPL',
    "eros_1": "NASA/JPL/JHUAPL",
    "juno_1": "NASA/JPL",
    "jupiter_1": 'NASA',
    "jupiter_2": 'NASA / Juno',
    "jupiter_europa_1": 'NASA Cassini',
    "kleopatra_1": 'ESO/Vernazza, Marchis et al',
    "1998 ky26_1": 'National Astronomical Observatory of Japan',
    "io_1": 'NASA Cassini',
    "iaeptus_1": 'NASA/JPL-Caltech/Space Science Institute',
    "Phobos_2": 'NASA',
    "deimos_1": '@HiRise',
    "ganymede_1": 'NASA',
    "europa_1": '@uhd2020',
    "europa_2": '@MAstronomer',
    "callisto_1": 'NASA Galileo',
    "castalia_1": 'JPL Image Processing Lab',
    "gaspra_1": 'NASA/JPL Galileo Spacecraft',
    "geographos_1": 'Steve Ostro et al JPL/NASA',
    "geographos_2": 'Steve Ostro et al JPL/NASA',
    "golevka_1": 'NASA/JPL',
    "saturn_1": 'JWST',
    "saturn_2": 'Cassini',
    "saturn_3": '@MAstronomer',
    "saturn_4": '@konstructivizm',
    "saturn_5": '@MAstronomer',
    "saturn_6": 'NASA Cassini',
    "enceladus_1": '@uhd2020',
    "titan_saturn_1": 'NASA Cassini',
    "titan_rhea_1": 'NASA Cassini',
    "titan_1": 'NASA JPL CALTECH U of Nantes U of Arizona',
    "titan_2": 'NASA',
    "rhea_1": 'NASA Cassini',
    "dione_1": 'NASA JPL SSI',
    "dione_2": 'NASA JPL SSI',
    "dione_3": 'NASA/JPL-Caltech/SSI/Kevin M. Gill',
    "dione_4": 'NASA Cassini',
    "tethys_1": '@uhd2020',
    "iapetus_1": 'NASA/JPL-Caltech/Space Science Institute',
    "iapetus_2": 'NASA Visualization Technology Applications and Development ',
    "ida_dactyl_1": 'NASA/JPL',
    "ida_dactyl_2": 'NASA/JPL',
    "uranus_1": 'NASA',
    "uranus_2": 'Hubble',
    "uranus_3": 'X-ray: NASA/CXO/Univ. College London/W. Dunn; Optical: W.M. Keck Obser.',
    "miranda_1": '@uhd2020',
    "miranda_2": 'NASA',
    "titania_1": 'NASA JPL',
    "titania_2": 'NASA',
    "toutatis_1": `Chang'e 2 probe Y. Jiang, J. Ji, J. Huang, S. Marchi, Y. Li & W.-Huen`,
    "oberon_1": 'NASA CALTECH JPL',
    "umbriel_1": 'NASA Voyager 2',
    "ariel_1": 'NASA',
    "neptune_1": 'NASA Voyager 2',
    "triton_1": 'NASA Voyager 2',
    "nereid_1": 'NASA Voyager 2',
    "pallas_1": 'Hubble Space Telescope/STScI 2007',
    "pallas_2": 'SPHERE, ESO/Vernazza et al. ',
    "proteus_1": 'NASA Voyager 2',
    "larissa_1": 'NASA Voyager 2',
    "despina_1": 'NASA Voyager 2',
    "galatea_1": 'NASA Voyager 2',
    "pluto_1": 'NASA New Horizons',
    "pluto_2": 'NASA New Horizons',
    "pluto_3": 'NASA New Horizons',
    "pluto_4": 'NASA',
    "charon_1": 'NASA New Horizons',
    "makemake_1": 'NASA',
    "eris_1": 'Samuel Oschin Telescope',
    "vesta_1": 'NASA/JPL-Caltech/UCAL/MPS/DLR/IDA'
    };